sample_mail_bodies = [
    {
        "message_id": 968,
        "message_body": "<div dir=\"ltr\">testing</div>\r\n\r\n<br>\r\n<span style=\"margin:0px;padding:0px;border:0px;vertical-align:baseline;color:rgb(68,68,68);font-family:&quot;Open Sans&quot;,sans-serif;background-color:rgb(255,255,255)\"><font size=\"2\">The views and opinions included in this email belong to their author and do not necessarily mirror the views and opinions of the company. Our employees are obliged not to make any defamatory clauses, infringe, or authorize infringement of any legal right. Therefore, the company will not take any liability for such statements included in emails. In case of any damages or other liabilities arising, employees are fully responsible for the content of their emails.</font></span>"
    },
    {
        "message_id": 970,
        "message_body": "<div dir=\"ltr\">Got it, thanks! <br clear=\"all\"><div><div dir=\"ltr\" class=\"gmail_signature\" data-smartmail=\"gmail_signature\"><div dir=\"ltr\">Regards,<div>Rupank Sahu</div><div><br></div></div></div></div><br></div><br><div class=\"gmail_quote\"><div dir=\"ltr\" class=\"gmail_attr\">On Fri, Mar 12, 2021 at 5:58 PM Gargi Riya &lt;<a href=\"mailto:tcs_indore@hellomailtest.msg91.com\">tcs_indore@hellomailtest.msg91.com</a>&gt; wrote:<br></div><blockquote class=\"gmail_quote\" style=\"margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);padding-left:1ex\">Your ticket id is #546 please use this for reference \r\n<p>Gargi Testing</p>\r\n \r\n\t\t     \r\n\t\t<img border=\"0\" width=\"1\" height=\"1\" src=\"http://mailer.msg91.com/api/open/Mzk0MzMy/cnVwYW5rQHdhbGtvdmVyLmlu\">\r\n\t\r\n</blockquote></div>\r\n\r\n<br>\r\n<span style=\"margin:0px;padding:0px;border:0px;vertical-align:baseline;color:rgb(68,68,68);font-family:&quot;Open Sans&quot;,sans-serif;background-color:rgb(255,255,255)\"><font size=\"2\">The views and opinions included in this email belong to their author and do not necessarily mirror the views and opinions of the company. Our employees are obliged not to make any defamatory clauses, infringe, or authorize infringement of any legal right. Therefore, the company will not take any liability for such statements included in emails. In case of any damages or other liabilities arising, employees are fully responsible for the content of their emails.</font></span>"
    },
    {
        "message_id": 986,
        "message_body": "<div dir=\"ltr\">testing<br clear=\"all\"><div><div dir=\"ltr\" class=\"gmail_signature\" data-smartmail=\"gmail_signature\"><div dir=\"ltr\"><br></div></div></div><br></div><br><div class=\"gmail_quote\"><div dir=\"ltr\" class=\"gmail_attr\">On Fri, Mar 12, 2021 at 5:59 PM Rupank sahu &lt;<a href=\"mailto:rupank@walkover.in\">rupank@walkover.in</a>&gt; wrote:<br></div><blockquote class=\"gmail_quote\" style=\"margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);padding-left:1ex\"><div dir=\"ltr\">Got it, thanks! <br clear=\"all\"><div><div dir=\"ltr\"><div dir=\"ltr\">Regards,<div>Rupank Sahu</div><div><br></div></div></div></div><br></div><br><div class=\"gmail_quote\"><div dir=\"ltr\" class=\"gmail_attr\">On Fri, Mar 12, 2021 at 5:58 PM Gargi Riya &lt;<a href=\"mailto:tcs_indore@hellomailtest.msg91.com\" target=\"_blank\">tcs_indore@hellomailtest.msg91.com</a>&gt; wrote:<br></div><blockquote class=\"gmail_quote\" style=\"margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);padding-left:1ex\">Your ticket id is #546 please use this for reference \r\n<p>Gargi Testing</p>\r\n \r\n\t\t     \r\n\t\t<img border=\"0\" width=\"1\" height=\"1\" src=\"http://mailer.msg91.com/api/open/Mzk0MzMy/cnVwYW5rQHdhbGtvdmVyLmlu\">\r\n\t\r\n</blockquote></div>\r\n</blockquote></div>\r\n\r\n<br>\r\n<span style=\"margin:0px;padding:0px;border:0px;vertical-align:baseline;color:rgb(68,68,68);font-family:&quot;Open Sans&quot;,sans-serif;background-color:rgb(255,255,255)\"><font size=\"2\">The views and opinions included in this email belong to their author and do not necessarily mirror the views and opinions of the company. Our employees are obliged not to make any defamatory clauses, infringe, or authorize infringement of any legal right. Therefore, the company will not take any liability for such statements included in emails. In case of any damages or other liabilities arising, employees are fully responsible for the content of their emails.</font></span>"
    },
    {
        "message_body": "<div>aur sunao, mai mail check kar raha hun</div><br><div class=\"gmail_quote_attribution\">On Mar 15 2021, at 6:56 pm, Deepam Gupta &lt;deepam@whozzat.com&gt; wrote:</div><blockquote><div>once more....</div><br><div class=\"gmail_quote_attribution\">On Mar 15 2021, at 6:55 pm, Deepam Gupta &lt;deepam@whozzat.com&gt; wrote:</div><blockquote><div>ek aur reply</div><br><div class=\"gmail_quote_attribution\">On Mar 15 2021, at 6:53 pm, Deepam Gupta &lt;deepam@whozzat.com&gt; wrote:</div><blockquote><br><div>hello,&nbsp; from deepam client</div><div class=\"gmail_quote_attribution\">On Mar 15 2021, at 4:25 pm, Deepam Gupta &lt;tcs_indore@hellomailtest.msg91.com&gt; wrote:</div><blockquote><div>Your ticket id is #530 please use this for reference</div><div>aur sunao bhiya</div></blockquote></blockquote></blockquote></blockquote><img class=\"mailspring-open\" alt=\"Sent from Mailspring\" width=\"0\" height=\"0\" style=\"border:0; width:0; height:0;\" src=\"https://link.getmailspring.com/open/7E425175-BECC-48D4-A956-70B0815FAA81@getmailspring.com?me=92761d93&amp;recipient=dGNzX2luZG9yZUBoZWxsb21haWx0ZXN0Lm1zZzkxLmNvbQ%3D%3D\">"
    },
    {
        "message_body": "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n<style type=\"text/css\" style=\"display:none;\"> P {margin-top:0;margin-bottom:0;} </style>\r\n</head>\r\n<body dir=\"ltr\">\r\n<div style=\"font-family: Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);\">\r\nyo, this is a check from outlook<br>\r\n</div>\r\n</body>\r\n</html>\r\n"
    },
    {
        "message_body": "<div><font style=\"font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;\">hello, of 16 march</font></div><div><font style=\"font-family:-apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;\">this is a link http://example.com/</font></div><br><div class=\"gmail_quote_attribution\">On Mar 15 2021, at 7:15 pm, Deepam Gupta &lt;deepam@whozzat.com&gt; wrote:</div><blockquote><div>aur sunao, mai mail check kar raha hun</div><br><div class=\"gmail_quote_attribution\">On Mar 15 2021, at 6:56 pm, Deepam Gupta &lt;deepam@whozzat.com&gt; wrote:</div><blockquote><div>once more....</div><br><div class=\"gmail_quote_attribution\">On Mar 15 2021, at 6:55 pm, Deepam Gupta &lt;deepam@whozzat.com&gt; wrote:</div><blockquote><div>ek aur reply</div><br><div class=\"gmail_quote_attribution\">On Mar 15 2021, at 6:53 pm, Deepam Gupta &lt;deepam@whozzat.com&gt; wrote:</div><blockquote><br><div>hello,&nbsp; from deepam client</div><div class=\"gmail_quote_attribution\">On Mar 15 2021, at 4:25 pm, Deepam Gupta &lt;tcs_indore@hellomailtest.msg91.com&gt; wrote:</div><blockquote><div>Your ticket id is #530 please use this for reference</div><div>aur sunao bhiya</div></blockquote></blockquote></blockquote></blockquote></blockquote>"
    },
    {
        "message_body": "<div dir=\"ltr\">ye msg maine gmail se bheja hai.</div><br><div class=\"gmail_quote\"><div dir=\"ltr\" class=\"gmail_attr\">On Tue, Mar 16, 2021 at 11:59 AM Deepam Gupta &lt;<a href=\"mailto:deepam@whozzat.com\">deepam@whozzat.com</a>&gt; wrote:<br></div><blockquote class=\"gmail_quote\" style=\"margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);padding-left:1ex\"><div><font style=\"font-family:-apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Roboto,&quot;Helvetica Neue&quot;,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;,&quot;Segoe UI Symbol&quot;\">hello, of 16 march</font></div><div><font style=\"font-family:-apple-system,BlinkMacSystemFont,&quot;Segoe UI&quot;,Roboto,&quot;Helvetica Neue&quot;,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;,&quot;Segoe UI Symbol&quot;\">this is a link <a href=\"http://example.com/\" target=\"_blank\">http://example.com/</a></font></div><br><div>On Mar 15 2021, at 7:15 pm, Deepam Gupta &lt;<a href=\"mailto:deepam@whozzat.com\" target=\"_blank\">deepam@whozzat.com</a>&gt; wrote:</div><blockquote><div>aur sunao, mai mail check kar raha hun</div><br><div>On Mar 15 2021, at 6:56 pm, Deepam Gupta &lt;<a href=\"mailto:deepam@whozzat.com\" target=\"_blank\">deepam@whozzat.com</a>&gt; wrote:</div><blockquote><div>once more....</div><br><div>On Mar 15 2021, at 6:55 pm, Deepam Gupta &lt;<a href=\"mailto:deepam@whozzat.com\" target=\"_blank\">deepam@whozzat.com</a>&gt; wrote:</div><blockquote><div>ek aur reply</div><br><div>On Mar 15 2021, at 6:53 pm, Deepam Gupta &lt;<a href=\"mailto:deepam@whozzat.com\" target=\"_blank\">deepam@whozzat.com</a>&gt; wrote:</div><blockquote><br><div>hello,  from deepam client</div><div>On Mar 15 2021, at 4:25 pm, Deepam Gupta &lt;<a href=\"mailto:tcs_indore@hellomailtest.msg91.com\" target=\"_blank\">tcs_indore@hellomailtest.msg91.com</a>&gt; wrote:</div><blockquote><div>Your ticket id is #530 please use this for reference</div><div>aur sunao bhiya</div></blockquote></blockquote></blockquote></blockquote></blockquote></blockquote></div>\r\n"
    }
]
