Responses=[
{
    "sno": 0,
    "message_body": "<html><head></head><body><div class=\"yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div dir=\"ltr\" data-setdir=\"false\">simple message</div></div></body></html>"
},
{
    "sno": 1,
    "message_body": "<html><head></head><body><div class=\"ydpea7bf815yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div></div>\r\n        <div dir=\"ltr\" data-setdir=\"false\">reply of single mail</div><div><br></div>\r\n        \r\n        </div><div id=\"yahoo_quoted_6684030347\" class=\"yahoo_quoted\">\r\n            <div style=\"font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:13px;color:#26282a;\">\r\n                \r\n                <div>\r\n                    On Wednesday, 24 March, 2021, 04:20:29 pm IST, gargi@whozzat.com &lt;gargi@whozzat.com&gt; wrote:\r\n                </div>\r\n                <div><br></div>\r\n                <div><br></div>\r\n                <div><div id=\"yiv1588705017\"><div><div class=\"yiv1588705017yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div dir=\"ltr\">simple message</div></div></div></div></div>\r\n            </div>\r\n        </div></body></html>"
},
{
    "sno": 2,
    "message_body": "<html><head></head><body><div class=\"yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div dir=\"ltr\" data-setdir=\"false\">This test is for para</div><div dir=\"ltr\" data-setdir=\"false\"><br></div><div dir=\"ltr\" data-setdir=\"false\">I am testing</div><div dir=\"ltr\" data-setdir=\"false\"><br></div><div dir=\"ltr\" data-setdir=\"false\">hello there&nbsp; &nbsp; hi</div></div></body></html>"
},
{
    "message_body": "<html><head></head><body><div class=\"ydpa64553d7yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div></div>\r\n        <div><br></div><div><div><div data-test-id=\"message-view-body\" class=\"ydp88a03194I_52qC ydp88a03194D_FY ydp88a03194W_6D6F\" style=\"width: 1333px;\"><div class=\"ydp88a03194msg-body ydp88a03194P_wpofO ydp88a03194mq_AS\" data-test-id=\"message-view-body-content\"><div class=\"ydp88a03194jb_0 ydp88a03194X_6MGW ydp88a03194N_6Fd5\"><div id=\"ydp88a03194yiv9304365745\"><div class=\"ydp88a03194yiv9304365745yahoo-style-wrap\" style=\"font-size: 16px;\"><div dir=\"ltr\">&lt;html&gt;</div><div dir=\"ltr\">&lt;body&gt;</div><div dir=\"ltr\">he jdkjfkd jnhrf</div><div dir=\"ltr\">&lt;/body&gt;</div><div dir=\"ltr\">&lt;/html&gt;</div></div></div></div></div><div class=\"ydp88a03194jb_0 ydp88a03194X_6MGW ydp88a03194N_6Fd5\"></div></div><div class=\"ydp88a03194H_7jIs ydp88a03194D_F ydp88a03194ab_C ydp88a03194Q_69H5 ydp88a03194E_36RhU\" data-test-id=\"toolbar-hover-area\"><div class=\"ydp88a03194D_F ydp88a03194W_6D6F ydp88a03194r_BN ydp88a03194gl_C\" data-test-id=\"card-toolbar\" style=\"width: 1361px;\"></div></div></div><br></div>\r\n        \r\n        </div><div id=\"yahoo_quoted_6790607554\" class=\"yahoo_quoted\">\r\n            <div style=\"font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:13px;color:#26282a;\">\r\n                \r\n                <div>\r\n                    On Wednesday, 24 March, 2021, 05:58:51 pm IST, gargi@whozzat.com &lt;gargi@whozzat.com&gt; wrote:\r\n                </div>\r\n                <div><br></div>\r\n                <div><br></div>\r\n                <div><div id=\"yiv9304365745\"><div><div class=\"yiv9304365745yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div dir=\"ltr\">&lt;html&gt;</div><div dir=\"ltr\">&lt;body&gt;</div><div dir=\"ltr\">he jdkjfkd jnhrf</div><div dir=\"ltr\">&lt;/body&gt;</div><div dir=\"ltr\">&lt;/html&gt;</div></div></div></div></div>\r\n            </div>\r\n        </div></body></html>"
},
{
    "message_body": "<html><head></head><body><div class=\"ydpa64553d7yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div></div>\r\n        <div><br></div><div><div><div data-test-id=\"message-view-body\" class=\"ydp88a03194I_52qC ydp88a03194D_FY ydp88a03194W_6D6F\" style=\"width: 1333px;\"><div class=\"ydp88a03194msg-body ydp88a03194P_wpofO ydp88a03194mq_AS\" data-test-id=\"message-view-body-content\"><div class=\"ydp88a03194jb_0 ydp88a03194X_6MGW ydp88a03194N_6Fd5\"><div id=\"ydp88a03194yiv9304365745\"><div class=\"ydp88a03194yiv9304365745yahoo-style-wrap\" style=\"font-size: 16px;\"><div dir=\"ltr\">&lt;html&gt;</div><div dir=\"ltr\">&lt;body&gt;</div><div dir=\"ltr\">he jdkjfkd jnhrf</div><div dir=\"ltr\">&lt;/body&gt;</div><div dir=\"ltr\">&lt;/html&gt;</div></div></div></div></div><div class=\"ydp88a03194jb_0 ydp88a03194X_6MGW ydp88a03194N_6Fd5\"></div></div><div class=\"ydp88a03194H_7jIs ydp88a03194D_F ydp88a03194ab_C ydp88a03194Q_69H5 ydp88a03194E_36RhU\" data-test-id=\"toolbar-hover-area\"><div class=\"ydp88a03194D_F ydp88a03194W_6D6F ydp88a03194r_BN ydp88a03194gl_C\" data-test-id=\"card-toolbar\" style=\"width: 1361px;\"></div></div></div><br></div>\r\n        \r\n        </div><div id=\"yahoo_quoted_6790607554\" class=\"yahoo_quoted\">\r\n            <div style=\"font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:13px;color:#26282a;\">\r\n                \r\n                <div>\r\n                    On Wednesday, 24 March, 2021, 05:58:51 pm IST, gargi@whozzat.com &lt;gargi@whozzat.com&gt; wrote:\r\n                </div>\r\n                <div><br></div>\r\n                <div><br></div>\r\n                <div><div id=\"yiv9304365745\"><div><div class=\"yiv9304365745yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div dir=\"ltr\">&lt;html&gt;</div><div dir=\"ltr\">&lt;body&gt;</div><div dir=\"ltr\">he jdkjfkd jnhrf</div><div dir=\"ltr\">&lt;/body&gt;</div><div dir=\"ltr\">&lt;/html&gt;</div></div></div></div></div>\r\n            </div>\r\n        </div></body></html>"
},
{
    "message_body": "<html><head></head><body><div class=\"yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div><img title=\"Inline image\" alt=\"Inline image\" src=\"cid:0fedc167-3540-ebcc-5746-bc5ebabe8715@yahoo.com\" class=\"yahoo-inline-image yahoo-loading\" draggable=\"false\" style=\"max-width: 800px;\" data-inlineimagemanipulating=\"true\" data-id=\"<0fedc167-3540-ebcc-5746-bc5ebabe8715@yahoo.com>\"><br><span></span><br></div></div></body></html>"
},
{
    "message_body": "<html><head></head><body><div class=\"ydpb2924891yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div></div>\r\n        <div dir=\"ltr\" data-setdir=\"false\">Image ka reply</div><div><br></div>\r\n        \r\n        </div><div id=\"yahoo_quoted_6899644736\" class=\"yahoo_quoted\">\r\n            <div style=\"font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:13px;color:#26282a;\">\r\n                \r\n                <div>\r\n                    On Wednesday, 24 March, 2021, 06:20:44 pm IST, gargi@whozzat.com &lt;gargi@whozzat.com&gt; wrote:\r\n                </div>\r\n                <div><br></div>\r\n                <div><br></div>\r\n                <div><div id=\"yiv8672502218\"><div><div class=\"yiv8672502218yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div><img title=\"Inline image\" alt=\"Inline image\" src=\"cid:lLjlCDfq1dMzVc4iuBYC\" class=\"yiv8672502218yahoo-inline-image yiv8672502218yahoo-loading\" style=\"max-width:800px;\" data-id=\"<0fedc167-3540-ebcc-5746-bc5ebabe8715@yahoo.com>\"><br><span></span><br></div></div></div></div></div>\r\n            </div>\r\n        </div></body></html>"
},
{
    "message_body": "<html><head></head><body><div class=\"ydpae3d7232yahoo-style-wrap\" style=\"font-family:Helvetica Neue, Helvetica, Arial, sans-serif;font-size:16px;\"><div><div><img title=\"Inline image\" alt=\"Inline image\" src=\"cid:175ca1e1-78f5-6cc4-1fb7-4e83eb46841f@yahoo.com\" class=\"yahoo-inline-image yahoo-loading\" draggable=\"false\" style=\"max-width: 800px;\" data-inlineimagemanipulating=\"true\" data-id=\"<175ca1e1-78f5-6cc4-1fb7-4e83eb46841f@yahoo.com>\"><br><span></span><br></div><div><br></div><div class=\"ydpae3d7232signature\"><div style=\"font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 16px;\"><div dir=\"ltr\" data-setdir=\"false\">thanks&nbsp;</div><div dir=\"ltr\" data-setdir=\"false\">yahoo gargi</div><div dir=\"ltr\" data-setdir=\"false\"><br></div><div dir=\"ltr\" data-setdir=\"false\"><br></div></div></div></div></div></body></html>"
}
]
